import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../src/context/AuthContext";
import { NotificationProvider } from "../src/context/NotificationContext";
import { Navbar } from "@components/shared/Navbar";
import { BookingProvider } from "@/src/context/BookingContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
            >
                <AuthProvider>
                    <BookingProvider>
                        <NotificationProvider>
                            <Navbar />
                            {children}
                        </NotificationProvider>
                    </BookingProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
